name: projectile-example
version: '0.0.0.1'
category: TODO
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: /Haskell-projectile
extra-source-files:
- README.md
executables:
  projectile-example:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - protolude
    - projectile
