name: projectile
version: '0.0.0.1'
category: TODO
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-projectile
tested-with: GHC==7.10.3 GHC==8.0.1 GHC==8.0.2
extra-source-files:
- README.md
- CHANGELOG.md
ghc-options:
- -Wall
# as recommended in:
# https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
dependencies:
- base            >=4.8 && <5.0
- protolude       >=0.1 && <0.2
- text            >=1.2 && <1.3
- deepseq         >=1.4 && <2.0
- safe-exceptions >=0.1 && <0.2
- path            >=0.5 && <0.6
- path-io         >=1.1 && <1.3
- vector          >=0.11 && <1.0
library:
  source-dirs: src
  exposed-modules:
  - Projectile
tests:
  projectile-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty       >=0.11 && <0.12
    - tasty-hunit >=0.9 && <0.10
    - tasty-rerun >=1.1 && <1.2
    - projectile
stability: alpha (experimental)
