name: projectile
version: '0.0.0.1'
category: TODO
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-projectile
tested-with: GHC==7.10.3 GHC==8.0.1 GHC==8.0.2
extra-source-files:
- README.md
- CHANGELOG.md
ghc-options:
- -Wall
# as recommended in:
# https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Werror
- -O2
dependencies:
- base
- protolude
- deepseq
- safe-exceptions
- path
- path-io
- vector
library:
  source-dirs: src
  exposed-modules:
  - Projectile
tests:
  projectile-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-rerun
    - text
    - projectile
stability: alpha (experimental)
